site_name: FenixTweaks

pages:
- Introduction: index.md
- Changelog: changelog.md
- Commands: commands.md
- Effect Persistence: effects.md
- Pools:
    - Pools: pools/pools.md
    - Structure: pools/structure.md
- Pool Types:
    - Block Harvest: pool-types/block-harvest.md
    - M&S Damage Dealt: pool-types/ms-damage-dealt.md

use_directory_urls: false

theme: readthedocs

markdown_extensions:
- admonition
- codehilite
